spring:
  application:
    # 应用名
    name: mindMap

#  security:
#    user:
#      name: root
#      password: root
#      roles: admin

  # MongoDB
  data:
    mongodb:
      uri: mongodb://localhost:27017/map
      password: 1314520
  #rabbitmq配置
  rabbitmq:
    username: guest
    password: guest
    addresses: localhost:5672
#      username: map

  datasource:
    url: jdbc:mysql://localhost:3306/map?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
  redis:
    database: 0
    port: 6379
    host: localhost
    password: 1314520
    lettuce:
      shutdown-timeout: 1000
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0


mybatis:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.example.mindmap.dao.entity

server:
  # 端口号
  port: 4000

mindMap:
  # 跨域配置
  cors:
    # 允许跨域的域名
    allow-origins:
      - http://localhost:1024
      - http://localhost:8080
  # 密钥


swagger_is_enable: true

jwt_secret: ES3215768H732E57HK12747329LX57842HXM23146

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
